### ISSUE TITLE
An error 0eFF occured

### ISSUE THREAD

**Issue by MadMax1960** [MadMax1960/Femc-Config-Adjuster#4]
[CrashLog_20240817_200737.txt](https://github.com/user-attachments/files/16645676/CrashLog_20240817_200737.txt)

![image](https://github.com/user-attachments/assets/168cb26c-4cca-4c8f-8406-d376a4bc8ce5)

**Comment by TheBestAstroNOT** [comment]
Is it fixed now or can u reproduce it?
