### ISSUE TITLE
Using the program also changes various other settings 

### ISSUE THREAD

**Issue by Brooksiebear19** [MadMax1960/Femc-Config-Adjuster#5]
After changing an option within the program, if you check back on the config in Reloaded-II, it will have adjusted some of the song settings and enabled gendered audio. This is in addition to making whatever changes you selected for the 2D and 3D settings within the config adjuster. It is not random in what options it selects, as it's seemingly defaulting back to some set of options. 

### Before adjusting your options within the config adjuster:
![image](https://github.com/user-attachments/assets/6c0dd40c-0902-4705-8055-36bc0ca0fe3a)

### After adjusting your options within the config adjuster:
![image](https://github.com/user-attachments/assets/80f857b3-b5c9-4833-a313-6629695694c7)

**Comment by TheBestAstroNOT** [comment]
This happens when the reloaded config gets corrupted while editing or the app experiences any sort of error opening the JSON. Did you close reloaded before running the app?

**Comment by Brooksiebear19** [comment]
Okay, after further testing it appears that it is not when I change things in the config adjuster but rather when I check the config in Reloaded-II after changing it is when the music options default. If I simply do not hit configure in Reloaded-II, the config works as it should when launching the game. If I do hit the config button in Reloaded-II, the music options become reset. This happens regardless of whether I have both programs open at the same time or not.

**Comment by TheBestAstroNOT** [comment]
Reloaded doesn't like its jsons being messed up, i don't think i can do anything about this tho

**Comment by TheBestAstroNOT** [comment]
Issue possibly fixed.
