### ISSUE TITLE
FemC Config Adjuster Crashes if ModUserConfig.json Doesn't Exist

### ISSUE THREAD

**Issue by scottoliver** [MadMax1960/Femc-Config-Adjuster#7]
In version 1.0.6 - after selecting the location of Reloaded-II.exe, an unhandled exception occurs when ModUserConfig.json does not exist and the app closes.

![Screenshot 2024-08-29 102051](https://github.com/user-attachments/assets/7325aa4d-5660-4864-9e1d-c95b46576388)

**Comment by TheBestAstroNOT** [comment]
Did you run the game once after installing the dependencies

**Comment by scottoliver** [comment]
Yes, game had already been run with FeMC mod.

**Comment by TheBestAstroNOT** [comment]
I honestly don't know why this might be caused cause I didn't add it calling the battlethemes moduserconfig anywhere. @RyoTune do you know anything abt this?
Also it did have the logic but the thing is we are currently transitioning to a different system to show errors so some auto-error handling is currently not functional.

**Comment by TheBestAstroNOT** [comment]
Bug fixed in v1.1.0
