### ISSUE TITLE
Config Adjuster incorrectly names settings in the config

### ISSUE THREAD

**Issue by Brooksiebear19** [MadMax1960/Femc-Config-Adjuster#8]
In the music section in particular, the program does not camel case certain settings which leads to incorrect settings being applied. For example: "KarmaAdv" and "MosqAdv" are incorrectly renamed to "Mosqadv" and "Karmaadv" after using the adjuster which causes those specific settings being changed when playing the game. This can be tested by editing the text file directly and incorrectly casing the naginata weapons parameter and setting it to false as they will then still display in game and upon opening the config in Reloaded-II it will display as true.

**Comment by TheBestAstroNOT** [comment]
Thanks for reporting this. I forgot to close this issue when I fixed the issue a lil while ago.

**Comment by TheBestAstroNOT** [comment]
Make sure you are using v1.1.0 or above
